In [1]:
#importing libraries
import pandas as pd
import numpy as np
import sklearn
#import keras
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
#Do this just once - No need to do any more
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials 
#Authenticate and create the PyDrive client.


auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

 

In [3]:
id = "1EcWRAgZcqNwH9g9Ko-TkZvAZQSaTeZOu" # 30P
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('30P.csv')  
P = pd.read_csv('30P.csv', header=None)

id = "1pfx3L4ivHItHUlgvQKlmZZPVWS14rt81" # 30Q
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('30Q.csv')  
Q = pd.read_csv('30Q.csv', header=None)

id = "1Dq9lxJ5AI-IzX2lSmeENdV7iUvWam4Ev" # 30V
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('30V.csv')  
V = pd.read_csv('30V.csv', header=None)

id = "1P1h6FFRnFN0YyXP9S-4nJt5uYVV_KaIf" # 30Va
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('30Va.csv') 
Va = pd.read_csv('30Va.csv', header=None)

In [ ]:
print(P.shape)
print(Q.shape)
print(V.shape)
print(Va.shape)

(500, 30)
(500, 30)
(500, 30)
(500, 30)


In [ ]:
num_train = P.shape[0]
num_bus = P.shape[1]


pi = 3.141592
Y = P.join(Q, lsuffix='_P', rsuffix='_Q')
X = Va.join(V, lsuffix='_V', rsuffix='_Va')
#Va = Va*pi/180

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

In [ ]:
ols = LinearRegression()
ols.fit(X,P)
ols.coef_.shape

(30, 60)

In [ ]:
ols.intercept_.shape

(30,)

In [ ]:
ols.intercept_

array([ 4.04630250e+00,  7.77715583e+00, -2.73952756e-01, -1.10148450e+00,
        0.00000000e+00,  0.00000000e+00, -2.38405175e+00,  5.26270073e+00,
        0.00000000e+00, -2.35738370e+00,  0.00000000e+00,  2.04033333e-03,
       -3.31501002e-01,  7.34324344e-01, -1.41514994e+00,  4.38397693e-01,
        8.26452184e-01,  2.74325265e-01, -4.54260508e-01, -4.09619494e-02,
       -1.96556695e+01,  2.52317856e+01,  3.23785511e+00, -1.94705698e+00,
        0.00000000e+00, -3.03040792e-01,  8.86085370e-01,  0.00000000e+00,
       -1.29104755e+00,  9.07025191e+00])

In [ ]:
coef = pd.DataFrame(ols.coef_)
intercept = pd.DataFrame(ols.intercept_)

In [ ]:
print(coef.shape)
print(intercept.shape)

(30, 60)
(30, 1)


In [ ]:
param = coef.join(intercept)

ValueError: ignored

In [ ]:
import numpy as np
from sklearn.linear_model import ARDRegression
import pandas as pd

X = Va.join(V, lsuffix='_Va', rsuffix='_V')
Y = P.join(Q, lsuffix='_P', rsuffix='_Q')

X_row,X_col = X.shape
Y_row,Y_col = Y.shape

In [ ]:
clf = ARDRegression()
clf.fit(X,P.iloc[:,0])

ARDRegression(alpha_1=1e-06, alpha_2=1e-06, compute_score=False, copy_X=True,
              fit_intercept=True, lambda_1=1e-06, lambda_2=1e-06, n_iter=300,
              normalize=False, threshold_lambda=10000.0, tol=0.001,
              verbose=False)

In [ ]:
P.iloc[:,0].shape

(500,)

In [ ]:
clf.coef_.shape

(60,)

In [ ]:
clf.coef_

array([ 0.        ,  0.        , -0.31088362,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        , 11.51489416,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ])

In [ ]:
clf.intercept_

-11.682666304905968

In [ ]:
arr1 = np.array(clf.coef_)
arr2 = np.array(clf.intercept_)

In [ ]:
arr2

array(-11.6826663)

In [ ]:
clf.coef_

array([ 0.        ,  0.        , -0.31088362,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        , 11.51489416,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ])

In [ ]:
arr = np.concatenate((arr1[:,None],arr2[None,None]))

In [ ]:
arr = arr.T

In [ ]:
arr.shape

(1, 61)

In [ ]:
from sklearn.linear_model import ARDRegression
from sklearn.model_selection import train_test_split
X = Va.join(V, lsuffix='_Va', rsuffix='_V')
Y = P
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15, random_state=42)

X_row,X_col = X_train.shape
Y_row,Y_col = Y_train.shape
    
judge_Y = ~(pd.DataFrame.sum(Y_train, axis=0) == np.zeros(Y_col))
    
X_blr = np.zeros((Y_col,X_col+1))
sigma_blr = np.zeros((Y_col,X_col))
    
for i in range(0,Y_col):
    if judge_Y[i]:
        y = Y_train.iloc[:,i]
        clf = ARDRegression()
        clf.threshold_lambda = 1000
            
        clf.fit(X_train, y)
        coef = clf.coef_.T
        X_blr[i, :] = np.hstack((coef,clf.intercept_))
    
Xp_temp = pd.DataFrame(X_blr)

In [ ]:
Xp_temp.shape

(30, 61)

In [ ]:
X_test.shape

(75, 60)

In [ ]:
d = pd.DataFrame(np.ones((X_test.shape[0], 1)))

In [ ]:
d.shape

(75, 1)

In [ ]:
X_test.shape

(75, 60)

In [ ]:
one = X_test.to_numpy()
two = d.to_numpy()
temp = pd.DataFrame(np.column_stack((one,two)))

In [ ]:
temp.shape

(75, 61)

In [ ]:
X_test = temp

In [ ]:
print(X_test.shape[0])
temp = pd.DataFrame(X_test.iloc[1,:])


75


In [ ]:
y = Xp_temp.dot(temp)

In [ ]:
pd.DataFrame(temp)

1
0   0.000000
1  -0.524646
2  -1.801209
3  -2.119328
4  -2.221255
..       ...
56  1.000000
57  0.988801
58  0.982682
59  0.970671
60  1.000000

[61 rows x 1 columns]

In [ ]:
y = y.T
y.shape

(1, 30)

In [ ]:
Y_train.iloc[2,:]

0     0.173195
1     0.420586
2    -0.028650
3    -0.077603
4     0.000000
5     0.000000
6    -0.241881
7    -0.299143
8     0.000000
9    -0.047945
10    0.000000
11   -0.124105
12    0.370285
13   -0.055050
14   -0.092903
15   -0.031194
16   -0.091936
17   -0.027494
18   -0.089957
19   -0.026061
20   -0.161349
21    0.224562
22    0.165383
23   -0.078194
24    0.000000
25   -0.028464
26    0.275852
27    0.000000
28   -0.024044
29   -0.086641
Name: 69, dtype: float64

In [ ]:
Xp_temp.dot(temp)

74
0   0.149064
1   0.405892
2  -0.023060
3  -0.075545
4   0.000000
5   0.000000
6  -0.205222
7  -0.295603
8   0.000000
9  -0.064419
10  0.000000
11 -0.118039
12  0.376583
13 -0.052047
14 -0.071703
15 -0.028702
16 -0.093003
17 -0.029032
18 -0.106290
19 -0.022622
20 -0.167343
21  0.224618
22  0.174877
23 -0.074589
24  0.000000
25 -0.046305
26  0.274178
27  0.000000
28 -0.021522
29 -0.099788

In [ ]:
# Finding P-error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
X = Va.join(V, lsuffix='_Va', rsuffix='_V')
Y = P
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15, random_state=42)

X_row,X_col = X_train.shape
Y_row,Y_col = Y_train.shape

judge_Y = ~(pd.DataFrame.sum(Y, axis=0) == np.zeros(Y_col))

X_blr = np.zeros((Y_col,X_col+1))
sigma_blr = np.zeros((Y_col,X_col))

for i in range(0,Y_col):
    if judge_Y[i]:
        y = Y.iloc[:,i]
        clf = ARDRegression()
        clf.threshold_lambda = threshold
        
        clf.fit(X_train, Y_train)
        coef = clf.coef_.T
        X_blr[i, :] = np.hstack((coef,clf.intercept_))

Xp_temp = pd.DataFrame(X_blr)
# Xp_temp = [30 x 61]
# X = [61 x 1]
# Y = [30 x 1]

# Adding intercept to X_test
one = X_test.to_numpy()
d = pd.DataFrame(np.ones((X_test.shape[0], 1)))
two = d.to_numpy()
X_test = pd.DataFrame(np.column_stack((one,two)))

# checkpoint
error = np.zeros((X_test.shape[0]))
for i in range(X_test.shape[0]):
    x = pd.DataFrame(X_test.iloc[i,:])
    y = Xp_temp.dot(x)
    y_pred = Y_train.iloc[i,:]
    curr = mean_absolute_error(y_pred, y)
    error[i] = curr

P_mape = error.mean()

NameError: ignored

In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
X = Va.join(V, lsuffix='_Va', rsuffix='_V')
Y = P
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15, random_state=42)

X_row,X_col = X_train.shape
Y_row,Y_col = Y_train.shape

judge_Y = ~(pd.DataFrame.sum(Y_train, axis=0) == np.zeros(Y_col))

X_blr = np.zeros((Y_col,X_col+1))
sigma_blr = np.zeros((Y_col,X_col))

for i in range(0,Y_col):
    if judge_Y[i]:
        y = Y_train.iloc[:,i]
        clf = ARDRegression()
        clf.threshold_lambda = 1000
        
        clf.fit(X_train, y)
        coef = clf.coef_.T
        X_blr[i, :] = np.hstack((coef,clf.intercept_))

Xp_temp = pd.DataFrame(X_blr)
# Xp_temp = [30 x 61]
# X = [61 x 1]
# Y = [30 x 1]

# Adding intercept to X_test
one = X_test.to_numpy()
d = pd.DataFrame(np.ones((X_test.shape[0], 1)))
two = d.to_numpy()
X_test = pd.DataFrame(np.column_stack((one,two)))

# checkpoint
error = np.zeros((X_test.shape[0]))
for i in range(X_test.shape[0]):
    x = pd.DataFrame(X_test.iloc[i,:])
    y = Xp_temp.dot(x)
    y_pred = Y_train.iloc[i,:]
    curr = mean_absolute_error(y_pred, y)
    error[i] = curr

P_mape = error.mean()

In [ ]:
P_mape

0.010867495620491765

In [ ]:
pd.DataFrame(X_test.iloc[0,:]).shape

(62, 1)

In [ ]:
error

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [ ]:
error.mean()

0.0

In [4]:
def BLR(P, Q, V, Va, num_train, num_bus):
    import numpy as np
    from sklearn.linear_model import ARDRegression
    import pandas as pd
    threshold = 1000
    
    # Finding Xp
    X = Va.join(V, lsuffix='_Va', rsuffix='_V')
    # Y = P.join(Q, lsuffix='_P', rsuffix='_Q')
    Y = P
    X_row,X_col = X.shape
    Y_row,Y_col = Y.shape
    
    judge_Y = ~(pd.DataFrame.sum(Y, axis=0) == np.zeros(Y_col))
    
    X_blr = np.zeros((Y_col,X_col+1))
    sigma_blr = np.zeros((Y_col,X_col))
    
    for i in range(0,Y_col):
        if judge_Y[i]:
            y = Y.iloc[:,i]
            clf = ARDRegression()
            clf.threshold_lambda = threshold
            
            clf.fit(X, y)
            coef = clf.coef_.T
            X_blr[i, :] = np.hstack((coef,clf.intercept_))
    
    Xp = pd.DataFrame(X_blr)

    # Finding Xq
    X = Va.join(V, lsuffix='_Va', rsuffix='_V')
    # Y = P.join(Q, lsuffix='_P', rsuffix='_Q')
    Y = Q
    X_row,X_col = X.shape
    Y_row,Y_col = Y.shape
    
    judge_Y = ~(pd.DataFrame.sum(Y, axis=0) == np.zeros(Y_col))
    
    X_blr = np.zeros((Y_col,X_col+1))
    sigma_blr = np.zeros((Y_col,X_col))
    
    for i in range(0,Y_col):
        if judge_Y[i]:
            y = Y.iloc[:,i]
            clf = ARDRegression()
            clf.threshold_lambda = threshold
            
            clf.fit(X, y)
            coef = clf.coef_.T
            X_blr[i, :] = np.hstack((coef,clf.intercept_))
    
    Xq = pd.DataFrame(X_blr)

    # Finding Xv
    X = P.join(Q, lsuffix='_P', rsuffix='_Q')
    # Y = Va.join(V, lsuffix='_Va', rsuffix='_V')
    Y = V
    X_row,X_col = X.shape
    Y_row,Y_col = Y.shape
    
    judge_Y = ~(pd.DataFrame.sum(Y, axis=0) == np.zeros(Y_col))
    
    X_blr = np.zeros((Y_col,X_col+1))
    sigma_blr = np.zeros((Y_col,X_col))
    
    for i in range(0,Y_col):
        if judge_Y[i]:
            y = Y.iloc[:,i]
            clf = ARDRegression()
            clf.threshold_lambda = threshold
            
            clf.fit(X, y)
            coef = clf.coef_.T
            X_blr[i, :] = np.hstack((coef,clf.intercept_))
    
    Xv = pd.DataFrame(X_blr)

    # Finding Xva
    X = P.join(Q, lsuffix='_P', rsuffix='_Q')
    # Y = Va.join(V, lsuffix='_Va', rsuffix='_V')
    Y = Va
    X_row,X_col = X.shape
    Y_row,Y_col = Y.shape
    
    judge_Y = ~(pd.DataFrame.sum(Y, axis=0) == np.zeros(Y_col))
    
    X_blr = np.zeros((Y_col,X_col+1))
    sigma_blr = np.zeros((Y_col,X_col))
    
    for i in range(0,Y_col):
        if judge_Y[i]:
            y = Y.iloc[:,i]
            clf = ARDRegression()
            clf.threshold_lambda = 1000
            
            clf.fit(X, y)
            coef = clf.coef_.T
            X_blr[i, :] = np.hstack((coef,clf.intercept_))
    
    Xva = pd.DataFrame(X_blr)

    # Finding P-error - Remove errors from above
    from sklearn.metrics import mean_absolute_percentage_error
    from sklearn.metrics import mean_absolute_error
    from sklearn.model_selection import train_test_split
    X = Va.join(V, lsuffix='_Va', rsuffix='_V')
    Y = P
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15, random_state=42)

    X_row,X_col = X_train.shape
    Y_row,Y_col = Y_train.shape
    
    judge_Y = ~(pd.DataFrame.sum(Y_train, axis=0) == np.zeros(Y_col))
    
    X_blr = np.zeros((Y_col,X_col+1))
    sigma_blr = np.zeros((Y_col,X_col))
    
    for i in range(0,Y_col):
        if judge_Y[i]:
            y = Y_train.iloc[:,i]
            clf = ARDRegression()
            clf.threshold_lambda = 1000
            
            clf.fit(X_train, y)
            coef = clf.coef_.T
            X_blr[i, :] = np.hstack((coef,clf.intercept_))
    
    Xp_temp = pd.DataFrame(X_blr)
    # Xp_temp = [30 x 61]
    # X = [61 x 1]
    # Y = [30 x 1]
    
    # Adding intercept to X_test
    one = X_test.to_numpy()
    d = pd.DataFrame(np.ones((X_test.shape[0], 1)))
    two = d.to_numpy()
    X_test = pd.DataFrame(np.column_stack((one,two)))

    # checkpoint
    error = np.zeros((X_test.shape[0]))
    for i in range(X_test.shape[0]):
        x = pd.DataFrame(X_test.iloc[i,:])
        y = Xp_temp.dot(x)
        y_pred = Y_train.iloc[i,:]
        curr = mean_absolute_percentage_error(y_pred, y)
        error[i] = curr
    
    P_mape = error.mean()
    
    # Finding Q error
    X = Va.join(V, lsuffix='_Va', rsuffix='_V')
    Y = Q
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15, random_state=42)

    X_row,X_col = X_train.shape
    Y_row,Y_col = Y_train.shape
    
    judge_Y = ~(pd.DataFrame.sum(Y_train, axis=0) == np.zeros(Y_col))
    
    X_blr = np.zeros((Y_col,X_col+1))
    sigma_blr = np.zeros((Y_col,X_col))
    
    for i in range(0,Y_col):
        if judge_Y[i]:
            y = Y_train.iloc[:,i]
            clf = ARDRegression()
            clf.threshold_lambda = 1000
            
            clf.fit(X_train, y)
            coef = clf.coef_.T
            X_blr[i, :] = np.hstack((coef,clf.intercept_))
    
    Xq_temp = pd.DataFrame(X_blr)
    # Xp_temp = [30 x 61]
    # X = [61 x 1]
    # Y = [30 x 1]
    
    # Adding intercept to X_test
    one = X_test.to_numpy()
    d = pd.DataFrame(np.ones((X_test.shape[0], 1)))
    two = d.to_numpy()
    X_test = pd.DataFrame(np.column_stack((one,two)))

    # checkpoint
    error = np.zeros((X_test.shape[0]))
    for i in range(X_test.shape[0]):
        x = pd.DataFrame(X_test.iloc[i,:])
        y = Xq_temp.dot(x)
        y_pred = Y_train.iloc[i,:]
        curr = mean_absolute_percentage_error(y_pred, y)
        error[i] = curr
    
    Q_mape = error.mean()
    
    # Finding V_error
    X = P.join(Q, lsuffix='_P', rsuffix='_Q')
    Y = V
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15, random_state=42)

    X_row,X_col = X_train.shape
    Y_row,Y_col = Y_train.shape
    
    judge_Y = ~(pd.DataFrame.sum(Y_train, axis=0) == np.zeros(Y_col))
    
    X_blr = np.zeros((Y_col,X_col+1))
    sigma_blr = np.zeros((Y_col,X_col))
    
    for i in range(0,Y_col):
        if judge_Y[i]:
            y = Y_train.iloc[:,i]
            clf = ARDRegression()
            clf.threshold_lambda = 1000
            
            clf.fit(X_train, y)
            coef = clf.coef_.T
            X_blr[i, :] = np.hstack((coef,clf.intercept_))
    
    Xv_temp = pd.DataFrame(X_blr)
    # Xp_temp = [30 x 61]
    # X = [61 x 1]
    # Y = [30 x 1]
    
    # Adding intercept to X_test
    one = X_test.to_numpy()
    d = pd.DataFrame(np.ones((X_test.shape[0], 1)))
    two = d.to_numpy()
    X_test = pd.DataFrame(np.column_stack((one,two)))

    # checkpoint
    error = np.zeros((X_test.shape[0]))
    for i in range(X_test.shape[0]):
        x = pd.DataFrame(X_test.iloc[i,:])
        y = Xv_temp.dot(x)
        y_pred = Y_train.iloc[i,:]
        curr = mean_absolute_error(y_pred, y)
        error[i] = curr
    
    V_mae = error.mean()
    
    # Finding Va error
    X = P.join(Q, lsuffix='_P', rsuffix='_Q')
    Y = Va
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15, random_state=42)

    X_row,X_col = X_train.shape
    Y_row,Y_col = Y_train.shape
    
    judge_Y = ~(pd.DataFrame.sum(Y_train, axis=0) == np.zeros(Y_col))
    
    X_blr = np.zeros((Y_col,X_col+1))
    sigma_blr = np.zeros((Y_col,X_col))
    
    for i in range(0,Y_col):
        if judge_Y[i]:
            y = Y_train.iloc[:,i]
            clf = ARDRegression()
            clf.threshold_lambda = 1000
            
            clf.fit(X_train, y)
            coef = clf.coef_.T
            X_blr[i, :] = np.hstack((coef,clf.intercept_))
    
    Xva_temp = pd.DataFrame(X_blr)
    # Xp_temp = [30 x 61]
    # X = [61 x 1]
    # Y = [30 x 1]
    
    # Adding intercept to X_test
    one = X_test.to_numpy()
    d = pd.DataFrame(np.ones((X_test.shape[0], 1)))
    two = d.to_numpy()
    X_test = pd.DataFrame(np.column_stack((one,two)))

    # checkpoint
    error = np.zeros((X_test.shape[0]))
    for i in range(X_test.shape[0]):
        x = pd.DataFrame(X_test.iloc[i,:])
        y = Xva_temp.dot(x)
        y_pred = Y_train.iloc[i,:]
        curr = mean_absolute_error(y_pred, y)
        error[i] = curr
    
    Va_mae = error.mean()


    return [Xp, Xq, Xv, Xva, P_mape, Q_mape, V_mae, Va_mae];

In [5]:
[Xp, Xq, Xv, Xva, P_mape, Q_mape, V_mae, Va_mae] = BLR(P, Q, V, Va, 500, 30);

ImportError: ignored